# Home_Learning_Task

1. Create a 1D array of numbers from 0 to 9

In [1]:
import numpy as np

In [2]:
# Creating 1 dimensional array

array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


2. Create a 3×3 NumPy array of all Boolean value Trues

In [3]:
array1 = np.ones((3,3))
print(array1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


3. Extract all odd numbers from array of 1-10

In [4]:
array2 = np.arange(1,10)
array2[array2 % 2 == 1]

array([1, 3, 5, 7, 9])

4.  Replace all odd numbers in an array of 1-10 with the value -1

In [5]:
array3 = np.arange(1,10)
odd_values = array3[array3 % 2 == 1] = -1
print(array3)

[-1  2 -1  4 -1  6 -1  8 -1]


5. Convert a 1D array to a 2D array with 2 rows

In [6]:
array4 = np.arange(6, 12).reshape(2, 3)
print(array4)

[[ 6  7  8]
 [ 9 10 11]]


6. Create two arrays a and b, stack these two arrays vertically use the np.dot and np.sum to calculate totals

In [7]:
x = np.arange(11, 20).reshape(3, 3)
y = np.arange(6, 15).reshape(3, 3) 
array5 = np.dot(x, y)

print(array5)

[[330 366 402]
 [411 456 501]
 [492 546 600]]


In [8]:
print(x)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [9]:
print(y)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [10]:
x = np.arange(11, 20).reshape(3, 3)
y = np.arange(6, 15).reshape(3, 3) 
array5 = np.dot(x, y)
print(array5)

total_sum = np.sum(array5)

print(total_sum)

[[330 366 402]
 [411 456 501]
 [492 546 600]]
4104


# Extension:

1. Create the following pattern without hardcoding. Use only NumPy functions.([1,1,1,2,2,2,3,3,3,1,2,3,1,2,3,1,2,3])

In [11]:
a = np.array([1,2,3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

2. In two arrays a ( 1,2,3,4,5) and b ( 4,5,6,7,8,9) – remove all repeating items present in array b

In [12]:
array_a = np.array([1,2,3,4,5])
array_b = np.array([4,5,6,7,8,9])
array6 = np.setdiff1d(array_a, array_b)
print(array6)

[1 2 3]


3. Get all items between 3 and 7 from a and b and sum themtogether

In [13]:
array_a = np.array([1,2,3,4,5])
array_b = np.array([4,5,6,7,8,9])
array7 = np.concatenate((array_a, array_b))
print(array7)

[1 2 3 4 5 4 5 6 7 8 9]


In [14]:
array7[np.logical_and(array7 > 3, array7 < 7)].sum()

24

In [15]:
array7[(array7 > 3) & (array7 < 7)].sum()

24